### ISSUE TITLE
[Please relocate] Bugs system not sending registration or password reset emails

### ISSUE THREAD

**Issue by willbprog127** [ghostbsd/station-tweak#4]
Apologies for making this issue in the wrong place, however when I try to either register or retrieve a forgotten password at https://issues.ghostbsd.org I do not get any emails from the system.  I have indeed checked the junk folder of my email and nothing there.  I want to submit some problem reports for GhostBSD and cannot due to this.

Thanks! :+1:

**Comment by ericbsd** [comment]
I did test it and it did work for me.

**Comment by willbprog127** [comment]
@ericbsd Hmm, I tried with two different e-mail addresses on two different systems and no e-mail back.  I have double-checked the 'Junk' folders and nothing there.  Odd.

**Comment by ericbsd** [comment]
can you send me your user name at ericturgeon.bsd at gmail dot com, I will be able to see it get created and maybe fix that for you.
